*nix: link to `libdl` and `libm` & Add library destination (CMake)
LLNL/Silo pull request #262
Opened 2022-05-25 16:55 UTC by henryleberre

This pull request contains the changes that were required for Silo to compile and link on my system using CMake. `libm` and `libdl` had to be given to the linker, and a destination library directory name (`lib`) had to be specified in Silo's `install` command.

2022-05-25 23:43 UTC, henryleberre commented
2nd commit: If a user manually specified their own `CMAKE_INSTALL_PREFIX`, Silo would still set its "default" prefix path. I fixed it by adding `if(CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT)`.

2022-06-02 19:38 UTC, henryleberre commented
@markcmiller86 Thank you for your quick reply. With these small tweaks, I was able to get Silo integrated into our CMake build system. I don't use a mac, but I just read that libdl is not a thing in that ecosystem. CMake conveniently provides `${CMAKE_DL_LIBS}` as a cross-platform replacement. I will make that change, and combine my commits by rebasing so that they don't clutter the repository's history. It should then be ready for review.

2022-06-03 00:04 UTC, markcmiller86 commented
@biagas when you have some time can you take a look?

2022-06-03 01:06 UTC, biagas requested changes

2022-06-03 01:06 UTC, biagas commented on CMakeLists.txt
> +        target_link_libraries(silock m dl)
```suggestion
        target_link_libraries(silock m ${CMAKE_DL_LIBS})
```

2022-06-03 01:06 UTC, biagas commented on CMakeLists.txt
> +target_link_libraries(silo "${CMAKE_DL_LIBS}")
```suggestion
target_link_libraries(silo ${CMAKE_DL_LIBS})
```

2022-06-03 01:06 UTC, biagas commented on CMakeLists.txt
> +target_link_libraries(silo "${CMAKE_DL_LIBS}")
Just wondering if ${CMAKE_DL_LIBS} should simply be added to line 577?

2022-06-03 01:06 UTC, biagas commented on tools/browser/CMakeLists.txt
> +target_link_libraries(browser "${CMAKE_DL_LIBS}")
```suggestion
target_link_libraries(browser ${CMAKE_DL_LIBS})
```

2022-06-03 15:55 UTC, merged

2022-06-03 15:56 UTC, markcmiller86 commented
thanks so much @henryleberre 🎉